# -*- coding: utf-8 -*-
"""style_5_27.ipynb
 
Automatically generated by Colaboratory.
 
Original file is located at
    https://colab.research.google.com/drive/1wy1oSnK01iiYRwUf4Rc4Y1rxyb_LTpu2
"""
 
# packages in this training file
 
from train_module import *
 
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
 
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow import keras
 
from tensorflow.keras.preprocessing import image
 
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from tensorflow.keras.layers.experimental.preprocessing import StringLookup
 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
import cv2
 
import matplotlib.image as mpimg
 
# connect with google while working on colab
from google.colab import drive
drive.mount('/content/drive')




bottom_base_model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])